# -*- coding: utf-8 -*-
"""Toxic_perspective.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13WyrG2GgtOWIEi2GChXNs0jV-xJCg5IB
"""

# Importing required libraries
import requests
from drive_functions import *
from detoxify import Detoxify
import pandas as pd
import time
import os
from datetime import date, timedelta
# Get today's date

current_date = date.today()

input_path = f".//Data//data_{current_date}.xlsx"
output_path = f".//Data//data_{current_date}.xlsx"
google_drive_folder = "1XQzVMy7k_mTrVSXduyaoRNmgtdGj3Bmj"

def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')



#df = pd.read_excel("Data/data_2023-07-28.xlsx")
df = pd.read_excel(input_path)


def add_toxicity_columns(df):
    # Initialize the model
    model = Detoxify('original')

    # Create new columns
    toxicity_scores = df['translated_message'].apply(lambda x: model.predict(x))

    for key in toxicity_scores.iloc[0].keys():
        df[key] = [score[key] for score in toxicity_scores]

    return df


df_new = add_toxicity_columns(df)
df_new.to_excel(output_path)

df_new = df_new.astype("str")

save_dataframe_to_drive(df_new, f"data_{current_date}.xlsx", google_drive_folder)
